Go straight
yuina-blend/kourobo-2020-ibarakiA pull request #2
Opened 2020-02-22 02:38 UTC by nanigasi-san

## 変更点
1. duty比の調整部分を消し、単純にコントローラーの情報をduty比に対応させるようにした
2. limit(float: 0.0~1.0)を設け、出力上限を設定

2020-02-22 03:34 UTC, yuina-blend requested changes

2020-02-22 03:34 UTC, yuina-blend commented on main(ライブラリなし).cpp
>          controller_axis = ps3.getLeftJoystickYaxis();
controller_axisがfloat型に変更されてるけど、getLeftJoystickYaxis関数は戻り値がint型なんでキャストしましょう（しなくても動くと思うけど明示的のがいい）

2020-02-22 04:22 UTC, nanigasi-san commented
頑張ったよ

2020-02-22 05:45 UTC, yuina-blend commented on main(ライブラリなし).cpp
>          controller_axis = ps3.getLeftJoystickYaxis();
やっぱなんでもない

2020-02-27 07:58 UTC, nanigasi-san commented
mbed使えないので閉じます

2020-02-27 07:58 UTC, closed without merging